### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by wang4386** [Xinslive/MiniPix#1]
很好看的项目，抽空我会发布到我的博客，下面是几点建议
增加标准S3存储协议
增加道德审查，可用国外免费ModerateContent或者接入百度图像审核或者自建nsfw服务
增加图片上传频率限制或大小限制，防止被切片上传

**Comment by Xinslive** [comment]
尽管我认为这是一个自用的图床，不必太复杂，但是你有需要的话我也可以尽力解决这几个问题

**Comment by Xinslive** [comment]
已支持本地储存，可通过挂载S3到本地的方式储存到S3。
合规审查功能已添加，开启后会拖累图片处理速度，自行考量。
已增加上传频率、大小限制。

**Comment by Xinslive** [comment]
我写bug的能力远比我写功能的能力高，尝试了一下，写出来的问题太多了

**Comment by Xinslive** [comment]
1、我认为支持本地储存已经够了，可以通过将S3的形式解决第一个需求。其他的如COS、七牛云等，同理。
2、增加道德审查对于自用是没有必要的，我尝试添加相关内容发现它有一个严重的问题：**拖慢处理速度**，这是不可忍受的。可以考虑使用如腾讯云图像安全等服务，进行后期审查。
3、这个容易，我新增加了一个validate.php文件，用于提供相关的功能

综上，你提的建议是有用的，可是我并没有足够的技术实力与动力去支撑我解决这些问题（本人从事会计行业，和计算机不搭边）。
