### ISSUE TITLE
配置好了上传图片正常，uploads也有文件也可以正常上传和删除，就是访问链接显示404

### ISSUE THREAD

**Issue by kingfly0927** [Xinslive/MiniPix#2]

**Comment by kingfly0927** [comment]
后台图片也显示不出来

**Comment by kingfly0927** [comment]
知道问题了，就是证书问题，就是没上证书的话，生成的链接默认带http的s,不上证书好像就会404，作者可以解决的话希望可以解决一下

**Comment by JLinMr** [comment]
> 知道问题了，就是证书问题，就是没上证书的话，生成的链接默认带http的s,不上证书好像就会404，作者可以解决的话希望可以解决一下

api.php 文件中搜https，自己改就行，图片还是建议使用证书
