### ISSUE TITLE
不知道是不是我的问题，png格式好像没有压缩，只是上传，后缀是jpg的就压缩了

### ISSUE THREAD

**Issue by kingfly0927** [Xinslive/MiniPix#3]

**Comment by Xinslive** [comment]
首席按你需要核实一下是否正确解除禁用 pcntl_signal 和 pcntl_alarm 函数。
目前默认的是png图片的处理逻辑是如果十秒钟的时间仍未成功转webp，也就是压缩失败的情况下，会保留原图。相关时间设置在api.php文件的第180行。
如果方便的话你可以把处理失败的png原图发送给我看看

**Comment by Xinslive** [comment]
本程序依赖PHP的 Fileinfo 、 Imagick 拓展，需要自行安装。依赖 pcntl 扩展（宝塔PHP默认已安装）

要求 pcntl_signal 和 pcntl_alarm 函数可用（需主动解除禁用）。

**Comment by Xinslive** [comment]
如果在演示站上可以压缩png图片，那就证明程序是没问题的

**Comment by kingfly0927** [comment]
你的演示站后台打不开，刚刚更新了新程序，png好像依旧压缩不了，环境也检查了都正常
