### ISSUE TITLE
发现的小问题，图片怎么这样了

### ISSUE THREAD

**Issue by kingfly0927** [Xinslive/MiniPix#5]
![PixPin_2024-08-03_11-17-41](https://github.com/user-attachments/assets/6b7fe0c2-3438-4fb7-894e-4840e97caded)

**Comment by kingfly0927** [comment]
这个是我的图片尺寸顺序读取错误所以反了，但是那个png格式的图片还是不压缩，但是看你的可以压缩，不知道是哪里出错了
![photo1(1)](https://github.com/user-attachments/assets/03eb4e22-6324-4182-bd2c-8fb1ee393fda)
这是那个png 图，

**Comment by Xinslive** [comment]
重新下载最新的api.php文件试试？另外依赖的相关函数要安装，还要解除特定函数的禁用状态
